---
- name: Common setup — base packages and system config
  hosts: jenkins
  become: true

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install base packages
      dnf:
        name:
          - wget
          - unzip
          - tar
          - git
          - jq
          - htop
          - net-tools
        state: present

    - name: Set timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata

    - name: Set hostname
      hostname:
        name: jenkins-server
